/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelasTheList;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadrastoCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadrastoCliente.class.getName());
    
    /**
     * Creates new form CadrastoCliente
     */
    public CadrastoCliente() {
        initComponents();
    }
    private boolean validacoes(){
        if (jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "o campo nome deve ser preechido");
            jTextFieldNome.requestFocus();
            return false;
            
        }
        
        if(jTextFieldCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "o campo CPF deve ser preechido");
            jTextFieldCpf.requestFocus();
            return false;
        }
        if(!jRadioButtonMasulino.isSelected() && jRadioButtonFeminino.isSelected()){
            JOptionPane.showMessageDialog(null, "opção de gênero não informada");
            return false;
            
        }
        
        if (!jCheckBoxTermos.isSelected()){
        JOptionPane.showMessageDialog(null, "os de ultilização não foram aceitos");
        return false;
    }
        
        return true;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenero = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonMasulino = new javax.swing.JRadioButton();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jCheckBoxTermos = new javax.swing.JCheckBox();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Cadrasto De Cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CPF");

        jTextFieldCpf.addActionListener(this::jTextFieldCpfActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cidade");

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001. Abatiá", "002. Adrianópolis", "003. Agudos do Sul", "004. Almirante Tamandaré", "005. Altamira do Paraná", "006. Alto Paraná", "007. Alto Paraíso", "008. Alto Piquiri", "009. Altônia", "010. Alvorada do Sul", "011. Amaporã", "012. Ampére", "013. Anahy", "014. Andirá", "015. Antonina", "016. Antônio Olinto", "017. Apucarana", "018. Arapongas", "019. Arapoti", "020. Arapuã", "021. Araruna", "022. Araucária", "023. Ariranha do Ivaí", "024. Assis Chateaubriand", "025. Astorga", "026. Atalaia", "027. Balsa Nova", "028. Bandeirantes", "029. Barbosa Ferraz", "030. Barra do Jacaré", "031. Barracão", "032. Bela Vista da Caroba", "033. Bela Vista do Paraíso", "034. Bituruna", "035. Boa Esperança", "036. Boa Esperança do Iguaçu", "037. Boa Vista da Aparecida", "038. Bocaiúva do Sul", "039. Bom Jesus do Sul", "040. Bom Sucesso", "041. Bom Sucesso do Sul", "042. Borrazópolis", "043. Braganey", "044. Brasilândia do Sul", "045. Cafeara", "046. Cafelândia", "047. Cafezal do Sul", "048. Califórnia", "049. Cambará", "050. Cambira", "051. Cambé", "052. Campina Grande do Sul", "053. Campina da Lagoa", "054. Campina do Simão", "055. Campo Bonito", "056. Campo Largo", "057. Campo Magro", "058. Campo Mourão", "059. Campo do Tenente", "060. Candói", "061. Cantagalo", "062. Capanema", "063. Capitão Leônidas Marques", "064. Carambeí", "065. Carlópolis", "066. Cascavel", "067. Castro", "068. Catanduvas", "069. Centenário do Sul", "070. Cerro Azul", "071. Chopinzinho", "072. Cianorte", "073. Cidade Gaúcha", "074. Clevelândia", "075. Colombo", "076. Colorado", "077. Congonhinhas", "078. Conselheiro Mairinck", "079. Contenda", "080. Corbélia", "081. Cornélio Procópio", "082. Coronel Domingos Soares", "083. Coronel Vivida", "084. Corumbataí do Sul", "085. Cruz Machado", "086. Cruzeiro do Oeste", "087. Cruzeiro do Sul", "088. Cruzmaltina", "089. Curitiba", "090. Curiúva", "091. Cândido de Abreu", "092. Céu Azul", "093. Diamante d'Oeste", "094. Diamante do Norte", "095. Diamante do Sul", "096. Dois Vizinhos", "097. Douradina", "098. Doutor Camargo", "099. Doutor Ulysses", "100. Engenheiro Beltrão", "101. Entre Rios do Oeste", "102. Enéas Marques", "103. Esperança Nova", "104. Espigão Alto do Iguaçu", "105. Farol", "106. Faxinal", "107. Fazenda Rio Grande", "108. Fernandes Pinheiro", "109. Figueira", "110. Flor da Serra do Sul", "111. Floraí", "112. Floresta", "113. Florestópolis", "114. Flórida", "115. Formosa do Oeste", "116. Foz do Iguaçu", "117. Foz do Jordão", "118. Francisco Alves", "119. Francisco Beltrão", "120. Fênix", "121. General Carneiro", "122. Godoy Moreira", "123. Grandes Rios", "124. Guairaçá", "125. Guamiranga", "126. Guapirama", "127. Guaporema", "128. Guaraci", "129. Guaraniaçu", "130. Guarapuava", "131. Guaraqueçaba", "132. Guaratuba", "133. Guaíra", "134. Honório Serpa", "135. Ibaiti", "136. Ibema", "137. Ibiporã", "138. Icaraíma", "139. Iguaraçu", "140. Iguatu", "141. Imbaú", "142. Imbituva", "143. Inajá", "144. Indianópolis", "145. Inácio Martins", "146. Ipiranga", "147. Iporã", "148. Iracema do Oeste", "149. Irati", "150. Iretama", "151. Itaguajé", "152. Itaipulândia", "153. Itambaracá", "154. Itambé", "155. Itapejara d'Oeste", "156. Itaperuçu", "157. Itaúna do Sul", "158. Ivaiporã", "159. Ivatuba", "160. Ivaté", "161. Ivaí", "162. Jaboti", "163. Jacarezinho", "164. Jaguapitã", "165. Jaguariaíva", "166. Jandaia do Sul", "167. Janiópolis", "168. Japira", "169. Japurá", "170. Jardim Alegre", "171. Jardim Olinda", "172. Jataizinho", "173. Jesuítas", "174. Joaquim Távora", "175. Jundiaí do Sul", "176. Juranda", "177. Jussara", "178. Kaloré", "179. Lapa", "180. Laranjal", "181. Laranjeiras do Sul", "182. Leópolis", "183. Lidianópolis", "184. Lindoeste", "185. Loanda", "186. Lobato", "187. Londrina", "188. Luiziana", "189. Lunardelli", "190. Lupionópolis", "191. Mallet", "192. Mamborê", "193. Mandaguari", "194. Mandaguaçu", "195. Mandirituba", "196. Manfrinópolis", "197. Mangueirinha", "198. Manoel Ribas", "199. Marechal Cândido Rondon", "200. Maria Helena", "201. Marialva", "202. Marilena", "203. Mariluz", "204. Marilândia do Sul", "205. Maringá", "206. Maripá", "207. Mariópolis", "208. Marmeleiro", "209. Marquinho", "210. Marumbi", "211. Matelândia", "212. Matinhos", "213. Mato Rico", "214. Mauá da Serra", "215. Medianeira", "216. Mercedes", "217. Mirador", "218. Miraselva", "219. Missal", "220. Moreira Sales", "221. Morretes", "222. Munhoz de Mello", "223. Nossa Senhora das Graças", "224. Nova Aliança do Ivaí", "225. Nova América da Colina", "226. Nova Aurora", "227. Nova Cantu", "228. Nova Esperança", "229. Nova Esperança do Sudoeste", "230. Nova Fátima", "231. Nova Laranjeiras", "232. Nova Londrina", "233. Nova Olímpia", "234. Nova Prata do Iguaçu", "235. Nova Santa Bárbara", "236. Nova Santa Rosa", "237. Nova Tebas", "238. Novo Itacolomi", "239. Ortigueira", "240. Ourizona", "241. Ouro Verde do Oeste", "242. Paiçandu", "243. Palmas", "244. Palmeira", "245. Palmital", "246. Palotina", "247. Paranacity", "248. Paranaguá", "249. Paranapoema", "250. Paranavaí", "251. Paraíso do Norte", "252. Pato Bragado", "253. Pato Branco", "254. Paula Freitas", "255. Paulo Frontin", "256. Peabiru", "257. Perobal", "258. Pinhais", "259. Pinhal de São Bento", "260. Pinhalão", "261. Pinhão", "262. Piraquara", "263. Piraí do Sul", "264. Pitanga", "265. Pitangueiras", "266. Piên", "267. Planaltina do Paraná", "268. Planalto", "269. Ponta Grossa", "270. Pontal do Paraná", "271. Porecatu", "272. Porto Amazonas", "273. Porto Barreiro", "274. Porto Rico", "275. Porto Vitória", "276. Prado Ferreira", "277. Pranchita", "278. Presidente Castelo Branco", "279. Primeiro de Maio", "280. Prudentópolis", "281. Pérola", "282. Pérola d'Oeste", "283. Quarto Centenário", "284. Quatiguá", "285. Quatro Barras", "286. Quatro Pontes", "287. Quedas do Iguaçu", "288. Querência do Norte", "289. Quinta do Sol", "290. Quitandinha", "291. Ramilândia", "292. Rancho Alegre", "293. Rancho Alegre d'Oeste", "294. Realeza", "295. Rebouças", "296. Renascença", "297. Reserva", "298. Reserva do Iguaçu", "299. Ribeirão Claro", "300. Ribeirão do Pinhal", "301. Rio Azul", "302. Rio Bom", "303. Rio Bonito do Iguaçu", "304. Rio Branco do Ivaí", "305. Rio Branco do Sul", "306. Rio Negro", "307. Rolândia", "308. Roncador", "309. Rondon", "310. Rosário do Ivaí", "311. Sabáudia", "312. Salgado Filho", "313. Salto do Itararé", "314. Salto do Lontra", "315. Santa Amélia", "316. Santa Cecília do Pavão", "317. Santa Cruz de Monte Castelo", "318. Santa Fé", "319. Santa Helena", "320. Santa Inês", "321. Santa Isabel do Ivaí", "322. Santa Izabel do Oeste", "323. Santa Lúcia", "324. Santa Maria do Oeste", "325. Santa Mariana", "326. Santa Mônica", "327. Santa Tereza do Oeste", "328. Santa Terezinha de Itaipu", "329. Santana do Itararé", "330. Santo Antônio da Platina", "331. Santo Antônio do Caiuá", "332. Santo Antônio do Paraíso", "333. Santo Antônio do Sudoeste", "334. Santo Inácio", "335. Sapopema", "336. Sarandi", "337. Saudade do Iguaçu", "338. Sengés", "339. Serranópolis do Iguaçu", "340. Sertaneja", "341. Sertanópolis", "342. Siqueira Campos", "343. Sulina", "344. São Carlos do Ivaí", "345. São Jerônimo da Serra", "346. São Jorge d'Oeste", "347. São Jorge do Ivaí", "348. São Jorge do Patrocínio", "349. São José da Boa Vista", "350. São José das Palmeiras", "351. São José dos Pinhais", "352. São João", "353. São João do Caiuá", "354. São João do Ivaí", "355. São João do Triunfo", "356. São Manoel do Paraná", "357. São Mateus do Sul", "358. São Miguel do Iguaçu", "359. São Pedro do Iguaçu", "360. São Pedro do Ivaí", "361. São Pedro do Paraná", "362. São Sebastião da Amoreira", "363. São Tomé", "364. Tamarana", "365. Tamboara", "366. Tapejara", "367. Tapira", "368. Teixeira Soares", "369. Telêmaco Borba", "370. Terra Boa", "371. Terra Rica", "372. Terra Roxa", "373. Tijucas do Sul", "374. Toledo", "375. Tomazina", "376. Três Barras do Paraná", "377. Tunas do Paraná", "378. Tuneiras do Oeste", "379. Tupãssi", "380. Turvo", "381. Ubiratã", "382. Umuarama", "383. Uniflor", "384. União da Vitória", "385. Uraí", "386. Ventania", "387. Vera Cruz do Oeste", "388. Verê", "389. Virmond", "390. Vitorino", "391. Wenceslau Braz", "392. Xambrê", "393. Ângulo" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Gênero");

        buttonGroupGenero.add(jRadioButtonMasulino);
        jRadioButtonMasulino.setText("Masculino");

        buttonGroupGenero.add(jRadioButtonFeminino);
        jRadioButtonFeminino.setText("Feminino");
        jRadioButtonFeminino.addActionListener(this::jRadioButtonFemininoActionPerformed);

        jCheckBoxTermos.setText("Aceito os termos de ultilização do sistema");
        jCheckBoxTermos.addActionListener(this::jCheckBoxTermosActionPerformed);

        jButtonSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(this::jButtonSalvarActionPerformed);

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCpf)
                                    .addComponent(jTextFieldNome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonMasulino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonFeminino)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jButtonSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(4, 4, 4)
                                        .addComponent(jComboBoxCidade, 0, 1, Short.MAX_VALUE))
                                    .addComponent(jCheckBoxTermos, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMasulino)
                    .addComponent(jRadioButtonFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxTermos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCpfActionPerformed

    private void jRadioButtonFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemininoActionPerformed

    private void jCheckBoxTermosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTermosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTermosActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       if(!validacoes()){
        return;
       }
       JOptionPane.showMessageDialog(null, "cadastro realizado com sucesso");
       
        System.exit(0);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadrastoCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGenero;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxTermos;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonMasulino;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
